package com.five.monkey.model;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.id
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.name
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.write_name
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    private String writeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.age
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.gender
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.phone
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.deleted
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    private Byte deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.id
     *
     * @return the value of author.id
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.id
     *
     * @param id the value for author.id
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.name
     *
     * @return the value of author.name
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.name
     *
     * @param name the value for author.name
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.write_name
     *
     * @return the value of author.write_name
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    public String getWriteName() {
        return writeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.write_name
     *
     * @param writeName the value for author.write_name
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    public void setWriteName(String writeName) {
        this.writeName = writeName == null ? null : writeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.age
     *
     * @return the value of author.age
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.age
     *
     * @param age the value for author.age
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.gender
     *
     * @return the value of author.gender
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.gender
     *
     * @param gender the value for author.gender
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.phone
     *
     * @return the value of author.phone
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.phone
     *
     * @param phone the value for author.phone
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.deleted
     *
     * @return the value of author.deleted
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.deleted
     *
     * @param deleted the value for author.deleted
     *
     * @mbg.generated Wed Apr 29 17:54:20 CST 2020
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }
}